# Generated by Django 2.2.3 on 2019-08-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdt_catalog', '0002_auto_20190806_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload_image_path'),
        ),
    ]
