# Generated by Django 2.2.3 on 2019-08-06 20:32

from django.db import migrations, models
import pdt_catalog.models


class Migration(migrations.Migration):

    dependencies = [
        ('pdt_catalog', '0003_auto_20190806_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=pdt_catalog.models.upload_image_path),
        ),
    ]
