# Generated by Django 2.2.3 on 2019-08-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdt_catalog', '0004_auto_20190806_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='def_slug'),
            preserve_default=False,
        ),
    ]
